const crypto=require('crypto');
const {Pool}=require('pg');
const pool=new Pool({connectionString:process.env.DATABASE_URL,max:5,idleTimeoutMillis:10000,connectionTimeoutMillis:10000,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:undefined});
const keys=['qid','passport','licence','certificate1','certificate2','certificate3','certificate4','certificate5'];
function hash(t){return crypto.createHash('sha256').update(t).digest('hex');}
function json(res,s,d){res.statusCode=s;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(d));}
async function auth(req){const h=req.headers.authorization||'',raw=h.startsWith('Bearer ')?h.slice(7):null;if(!raw)return null;const c=await pool.connect();try{const r=await c.query(`SELECT u.id,u.username,u.role FROM app_sessions s JOIN app_users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND u.status='Active'`,[hash(raw)]);return r.rows[0]||null;}finally{c.release();}}
async function audit(u,details){const c=await pool.connect();try{await c.query(`INSERT INTO audit_log(user_id,username,action,page,details) VALUES($1,$2,$3,$4,$5)`,[u.id,u.username,'Updated employee document expiry','Staff/Employee',details]);}finally{c.release();}}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject);});}
module.exports=async function(req,res){if(req.method!=='PUT')return json(res,405,{error:'PUT required'});try{const u=await auth(req);if(!u)return json(res,401,{error:'Authentication required'});if(!['Administrator','Supervisor','HR','Data Entry'].includes(u.role))return json(res,403,{error:'Your role is view-only for data changes'});const b=await body(req);const id=String(b.employeeId||''),key=String(b.docKey||'');if(!id||!keys.includes(key))return json(res,400,{error:'Invalid employee document target'});const c=await pool.connect();try{const r=await c.query(`UPDATE employee_documents SET expiry_date=$1,updated_at=now(),uploaded_by=$2 WHERE employee_id=$3 AND doc_key=$4 RETURNING id,doc_key,expiry_date`,[b.expiryDate||null,u.id,id,key]);if(!r.rows[0])return json(res,404,{error:'Document not found'});await audit(u,{employeeDbId:id,docKey:key,expiryDate:b.expiryDate||null});return json(res,200,{ok:true,document:r.rows[0]});}finally{c.release();}}catch(e){console.error('Employee expiry API:',e);return json(res,500,{error:e.message||'Expiry update failed'});}};
